workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build iOS Application
        script: |
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign --suppress-analytics
    artifacts:
      - build/ios/iphoneos/Runner.app
