workflows:
  ios-workflow:
    name: iOS Build
    instance_type: mac_mini_m1
    max_build_duration: 30
    environment:
      flutter: stable
      xcode: latest
    scripts:
      - name: Create iOS folder if missing & Get packages
        script: |
          if [ ! -d "ios" ]; then
            flutter create . --platforms=ios
          fi
          flutter pub get
      - name: Build iOS Application
        script: |
          flutter build ios --simulator --no-codesign
    artifacts:
      - build/ios/iphonesimulator/Runner.app
